import './globals.css'
import localFont from 'next/font/local'
import Image from 'next/image'

const hana = localFont({
        src: [
                {
                        path: '../fonts/hana/Hana2-Heavy.ttf',
                        weight: '900',
                        style: 'extrabold',
                },
                {
                        path: '../fonts/hana/Hana2-Bold.ttf',
                        weight: '700',
                        style: 'bold',
                },
                {
                        path: '../fonts/hana/Hana2-Medium.ttf',
                        weight: '500',
                        style: 'semibold',
                },
                {
                        path: '../fonts/hana/Hana2-Regular.ttf',
                        weight: '400',
                        style: 'regular',
                },
                {
                        path: '../fonts/hana/Hana2-Light.ttf',
                        weight: '300',
                        style: 'light',
                },
        ],
        display: 'swap',
        variable: '--font-hana',
})

const apple = localFont({
        src: [
                {
                        path: '../fonts/apple/AppleSDGothicNeoEB.ttf',
                        weight: '900',
                        style: 'extrabold',
                },
                {
                        path: '../fonts/apple/AppleSDGothicNeoB.ttf',
                        weight: '700',
                        style: 'bold',
                },
                {
                        path: '../fonts/apple/AppleSDGothicNeoM.ttf',
                        weight: '500',
                        style: 'semibold',
                },
                {
                        path: '../fonts/apple/AppleSDGothicNeoR.ttf',
                        weight: '400',
                        style: 'regular',
                },
                {
                        path: '../fonts/apple/AppleSDGothicNeoL.ttf',
                        weight: '300',
                        style: 'light',
                },
                {
                        path: '../fonts/apple/AppleSDGothicNeoUL.ttf',
                        weight: '200',
                        style: 'demilight',
                },
                {
                        path: '../fonts/apple/AppleSDGothicNeoT.ttf',
                        weight: '100',
                        style: 'thin',
                },
        ],
        display: 'swap',
        variable: '--font-apple',
})

export const metadata = {
        title: 'Hana DID',
        description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
        return (
                <html
                        lang="en"
                        className={`${hana.variable} ${apple.variable}`}>
                        <body>
                                {children}
                                <Image
                                        src="/images/bg-2400.png"
                                        width={3820}
                                        height={2160}
                                        alt=""
                                        className="layout-background"
                                />
                        </body>
                </html>
        )
}
